// ==========================================================
// Supabase Client Configuration
// This file is automatically generated. Extended for clarity
// ==========================================================

import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

/* ========================================================= */
/* ENV VARIABLES                                             */
/* ========================================================= */

const SUPABASE_URL: string = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY: string = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/* ========================================================= */
/* BASIC VALIDATION (light improvement)                      */
/* ========================================================= */

if (!SUPABASE_URL) {
  console.warn('⚠️ Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
}

/* ========================================================= */
/* CLIENT OPTIONS                                            */
/* ========================================================= */

const options = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,

    // Slight improvement: detect session in URL (OAuth use case)
    detectSessionInUrl: true,
  },

  global: {
    headers: {
      'x-application-name': 'attendance-tracker-app',
    },
  },
};

/* ========================================================= */
/* CREATE CLIENT                                             */
/* ========================================================= */

export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  options
);

/* ========================================================= */
/* OPTIONAL HELPER FUNCTIONS (minimal additions)             */
/* ========================================================= */

/**
 * Get current session safely
 */
export const getCurrentSession = async () => {
  const { data, error } = await supabase.auth.getSession();

  if (error) {
    console.error('Error fetching session:', error.message);
    return null;
  }

  return data.session;
};

/**
 * Get current user safely
 */
export const getCurrentUser = async () => {
  const { data, error } = await supabase.auth.getUser();

  if (error) {
    console.error('Error fetching user:', error.message);
    return null;
  }

  return data.user;
};

/**
 * Sign out helper
 */
export const signOutUser = async () => {
  const { error } = await supabase.auth.signOut();

  if (error) {
    console.error('Error signing out:', error.message);
  }
};

/* ========================================================= */
/* USAGE NOTE                                                */
/* ========================================================= */

// Import like this in your app:
// import { supabase } from "@/integrations/supabase/client";

/* ========================================================= */
/* END                                                       */
/* ========================================================= */
